#!/bin/bash

function setjava () {

    JDK_HOME=
    case  $1  in
        oracle-jdk8u221)       
            JDK_HOME="/opt/java/oracle-jdk8u221"
            ;;
        *)
    esac 

    if [ ! -z "$JDK_HOME" ]; then
        $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/setjava $JDK_HOME
    else
        OPTIONS=
        printf "\"$1\" is not a valid java choice, available options are:
    oracle-jdk8u221\n"
    fi
}

if  [ ! -z "$(command -v complete)" ]; then
    complete -W "oracle-jdk8u221" setjava
fi

